// AUTO-GENERATED by @lovable.dev/mcp-js — do not edit. Regenerated by the Vite plugin.
// To take ownership, delete this banner line; the plugin then leaves the file alone.
// supabase function: mcp
// Bundled from src/lib/mcp/index.ts by @lovable.dev/mcp-js.
// src/lib/mcp/index.ts
import { defineMcp } from "npm:@lovable.dev/mcp-js@0.26.1";

// src/lib/mcp/tools/list-exam-categories.ts
import { defineTool } from "npm:@lovable.dev/mcp-js@0.26.1";
import { examCategories } from "npm:@/data/examData";
var list_exam_categories_default = defineTool({
  name: "list_exam_categories",
  title: "List exam categories",
  description: "List all competitive exam categories offered on the platform (Banking & Insurance, SSC, Railways, UPSC, State PSC and more) with descriptions and enrolment counts.",
  inputSchema: {},
  annotations: { readOnlyHint: true, idempotentHint: true, openWorldHint: false },
  handler: () => {
    const rows = examCategories.map((c) => ({
      id: c.id,
      name: c.name,
      description: c.description,
      studentsEnrolled: c.studentsEnrolled,
      examsAvailable: c.examsAvailable,
      isPopular: c.isPopular
    }));
    return {
      content: [{ type: "text", text: JSON.stringify(rows, null, 2) }],
      structuredContent: { categories: rows }
    };
  }
});

// src/lib/mcp/tools/list-exams.ts
import { defineTool as defineTool2, ToolError } from "npm:@lovable.dev/mcp-js@0.26.1";
import { z } from "npm:zod@^3.23.8";
import { examCategories as examCategories2, getExamsByCategory } from "npm:@/data/examData";
var list_exams_default = defineTool2({
  name: "list_exams",
  title: "List exams in a category",
  description: "List the individual exams available inside one exam category. Use `list_exam_categories` first to get a valid category id.",
  inputSchema: {
    categoryId: z.string().min(1).describe("Exam category id, e.g. 'banking-insurance' or 'ssc'.")
  },
  annotations: { readOnlyHint: true, idempotentHint: true, openWorldHint: false },
  handler: ({ categoryId }) => {
    const known = examCategories2.some((c) => c.id === categoryId);
    const exams = getExamsByCategory(categoryId);
    if (!known && exams.length === 0) {
      throw new ToolError(
        `Unknown category '${categoryId}'. Valid ids: ${examCategories2.map((c) => c.id).join(", ")}`
      );
    }
    const rows = exams.map((e) => ({ id: e.id, name: e.name, isPopular: e.isPopular }));
    return {
      content: [{ type: "text", text: JSON.stringify(rows, null, 2) }],
      structuredContent: { categoryId, exams: rows }
    };
  }
});

// src/lib/mcp/tools/search-courses.ts
import { defineTool as defineTool3 } from "npm:@lovable.dev/mcp-js@0.26.1";
import { z as z2 } from "npm:zod@^3.23.8";
import { courses } from "npm:@/data/courseData";
var search_courses_default = defineTool3({
  name: "search_courses",
  title: "Search courses",
  description: "Search the public course catalog by keyword, category and course type (Prelims, Mains, Interview, Complete). Returns price, rating, duration and content counts.",
  inputSchema: {
    query: z2.string().nullable().describe("Free-text search over course title, instructor and subjects. Null for all."),
    category: z2.string().nullable().describe("Course category id to filter by, e.g. 'banking'. Null for all."),
    type: z2.enum(["Prelims", "Mains", "Interview", "Complete"]).nullable().describe("Course type filter. Null for all."),
    limit: z2.number().int().nullable().describe("Max results to return. Null defaults to 20.")
  },
  annotations: { readOnlyHint: true, idempotentHint: true, openWorldHint: false },
  handler: ({ query, category, type, limit }) => {
    const q = query?.trim().toLowerCase();
    const rows = courses.filter((c) => category ? c.category === category : true).filter((c) => type ? c.type === type : true).filter(
      (c) => q ? [c.title, c.instructor, ...c.subjects].join(" ").toLowerCase().includes(q) : true
    ).slice(0, Math.max(1, Math.min(limit ?? 20, 50))).map((c) => ({
      id: c.id,
      title: c.title,
      instructor: c.instructor,
      category: c.category,
      type: c.type,
      price: c.price,
      originalPrice: c.originalPrice ?? null,
      rating: c.rating,
      duration: c.duration,
      studentsCount: c.studentsCount,
      subjects: c.subjects,
      chaptersCount: c.chaptersCount,
      videosCount: c.videosCount,
      testsCount: c.testsCount
    }));
    return {
      content: [{ type: "text", text: JSON.stringify(rows, null, 2) }],
      structuredContent: { count: rows.length, courses: rows }
    };
  }
});

// src/lib/mcp/tools/get-course.ts
import { defineTool as defineTool4, ToolError as ToolError2 } from "npm:@lovable.dev/mcp-js@0.26.1";
import { z as z3 } from "npm:zod@^3.23.8";
import { getCourseById, getInstructorById } from "npm:@/data/courseData";
var get_course_default = defineTool4({
  name: "get_course",
  title: "Get course details",
  description: "Get full public details for a single course by id, including instructor profile. Use `search_courses` to find ids.",
  inputSchema: { courseId: z3.string().min(1).describe("Course id.") },
  annotations: { readOnlyHint: true, idempotentHint: true, openWorldHint: false },
  handler: ({ courseId }) => {
    const course = getCourseById(courseId);
    if (!course) throw new ToolError2(`No course found with id '${courseId}'.`);
    const instructor = getInstructorById(course.instructorId) ?? null;
    const payload = {
      ...course,
      instructorProfile: instructor ? {
        id: instructor.id,
        name: instructor.name,
        specialization: instructor.specialization,
        experience: instructor.experience,
        rating: instructor.rating,
        studentsCount: instructor.studentsCount
      } : null
    };
    return {
      content: [{ type: "text", text: JSON.stringify(payload, null, 2) }],
      structuredContent: { course: payload }
    };
  }
});

// src/lib/mcp/tools/list-exam-notifications.ts
import { defineTool as defineTool5 } from "npm:@lovable.dev/mcp-js@0.26.1";
import { z as z4 } from "npm:zod@^3.23.8";
import { examNotifications } from "npm:@/data/examNotificationData";
var list_exam_notifications_default = defineTool5({
  name: "list_exam_notifications",
  title: "List exam notifications",
  description: "List public exam notifications with application windows, payment deadlines, exam dates and official links. Optionally filter to one exam category or only upcoming exams.",
  inputSchema: {
    categoryId: z4.string().nullable().describe("Exam category id to filter by. Null for all categories."),
    upcomingOnly: z4.boolean().nullable().describe("When true, return only exams flagged as upcoming. Null means no filter.")
  },
  annotations: { readOnlyHint: true, idempotentHint: true, openWorldHint: false },
  handler: ({ categoryId, upcomingOnly }) => {
    const rows = examNotifications.filter((n) => categoryId ? n.categoryIds.includes(categoryId) : true).filter((n) => upcomingOnly ? n.isUpcoming : true).map((n) => ({
      id: n.id,
      examName: n.examName,
      categoryIds: n.categoryIds,
      applicationStart: n.applicationPeriod.startDate,
      applicationEnd: n.applicationPeriod.endDate,
      paymentLastDate: n.paymentLastDate,
      examDate: n.examDate,
      applyStatus: n.applyStatus,
      resultStatus: n.resultStatus,
      isUpcoming: n.isUpcoming,
      links: n.urls
    }));
    return {
      content: [{ type: "text", text: JSON.stringify(rows, null, 2) }],
      structuredContent: { count: rows.length, notifications: rows }
    };
  }
});

// src/lib/mcp/index.ts
var mcp_default = defineMcp({
  name: "updatedexam",
  title: "Updatedexam",
  version: "0.1.0",
  instructions: "Public tools for Updatedexam, an Indian competitive-exam preparation platform. Browse exam categories and exams with `list_exam_categories` and `list_exams`, explore the course catalog with `search_courses` and `get_course`, and check application windows and exam dates with `list_exam_notifications`. All data returned is public catalog content; no student accounts or personal data are exposed.",
  tools: [list_exam_categories_default, list_exams_default, search_courses_default, get_course_default, list_exam_notifications_default]
});

// lovable-mcp-supabase-entry.ts
import { createSupabaseHandler } from "npm:@lovable.dev/mcp-js@0.26.1/stacks/supabase";
Deno.serve(createSupabaseHandler(mcp_default, { functionName: "mcp" }));
